---
- hosts: localhost
  remote_user: lukehowsam
  tasks:
    - name: Install "unzip" pkg
      apt:
        name: unzip
        state: present
      tags:
        - config

    - name: Install "htop" pkg
      apt:
        name: htop
        state: present
      tags:
        - config

    - name: Install "vim" pkg
      apt:
        name: vim
        state: present
      tags:
        - config

    - name: Install "tmux" pkg
      apt:
        name: tmux
        state: present
      tags:
        - config 

    - name: Install "nmap" pkg
      apt:
        name: nmap
        state: present
      tags:
        - config


    - name: Install "bridge-utils" pkg
      apt:
        name: bridge-utils
        state: present
      tags:
        - config

    - name: Install "cmake" pkg
      apt:
        name: cmake
        state: present
      tags:
        - config

    - name: Install "libreoffice" pkg
      apt:
        name: libreoffice
        state: present
      tags:
        - config

    - name: Install "build-essential" pkg
      apt:
        name: unzip
        state: present
      tags: 
        - config 


    - name: Install "dialog" pkg
      apt:
        name: dialog
        state: present
      tags:
        - config

    - name: Install "python3-pip" pkg
      apt:
        name: python3-pip
        state: present
      tags:
        - config

    - name: Install "python3-setuptools" pkg
      apt:
        name: python3-setuptools
        state: present
      tags:
        - config

    - name: Install "lm-sensors" pkg
      apt:
        name: lm-sensors
        state: present
      tags:
        - config

    - name: Install "pulseaudio" pkg
      apt:
        name: pulseaudio
        state: present
      tags:
        - config

    - name: Install "pavucontrol" pkg
      apt:
        name: pavucontrol
        state: present
      tags:
        - config

    - name: Install "at" pkg
      apt:
        name: at
        state: present
      tags:
        - config

    - name: Install "bluez" pkg
      apt:
        name: bluez
        state: present
      tags:
        - config


    - name: Install "blueman" pkg
      apt:
        name: blueman
        state: present
      tags:
        - config

    - name: Install "pulseaudio-module-bluetooth" pkg
      apt:
        name: pulseaudio-module-bluetooth
        state: present
      tags:
        - config

    - name: Install "ubuntu-desktop" pkg
      apt:
        name: ubuntu-desktop
        state: present
      tags:
        - config

    - name: Install "unity-control-center" pkg
      apt:
        name: unity-control-center
        state: present
      tags:
        - config

    - name: create custom dirs
      file:
        path: /home/lukehowsam/srv
        state: directory
      tags:
        - config

    - name: create custom dirs
      file:
        path: /home/lukehowsam/srv/dev
        state: directory
      tags:
        - config


    - name: Install "expo-cli" node.js package globally.
      npm:
        name: expo-cli
        global: yes
      tags:
        - npm

    - name: Install "react-native-cli" node.js package globally.
      npm:
        name: react-native-cli
        global: yes
      tags:
        - npm
                
    - name: Install "vercel" node.js package globally.
      npm:
        name: vercel
        global: yes
      tags:
        - npm


    - name: Install "lite-server" node.js package globally.
      npm:
        name: lite-server
        global: yes
      tags:
        - npm
        
    - name: Install "ncu" node.js package globally.
      npm:
        name: ncu
        global: yes
      tags:
        - npm
        
    - name: Install "typescript" node.js package globally.
      npm:
        name: typescript
        global: yes
      tags:
        - npm

    - name: Install "nodemon" node.js package globally.
      npm:
        name: nodemon
        global: yes
      tags:
        - npm

    - name: Install "artillery" node.js package globally.
      npm:
        name: artillery
        global: yes
      tags:
        - npm

    - name: Install "netlify-cli" node.js package globally 
      npm: 
        name: netlify-cli 
        global: yes 
      tags: 
        - Deployment 

    - name: Install "gatsby-cli" node.js package globally 
      npm: 
        name: gatsby-cli
        global: yes 
      tags: 
        - npm 

    - name: Install "pa11y" node.js package globally 
      npm: 
        name: pa11y 
        global: yes 
      tags: 
        - npm 