version: "3"
services:
  db:
    container_name: ees-mssql
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    volumes:
    #   - ../data/ees-mssql:/var/opt/mssql/data
    #   - ../data/sql-scripts:/scripts/
    environment:
      SA_PASSWORD: "Your_Password123"
      ACCEPT_EULA: "Y"
    command:
      - /bin/bash
      - -c
      - |
        # Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &
        # Wait 30 seconds for it to be available
        sleep 30
        # Run the setup script to create the two databases
        # /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -l 30 -e -i /scripts/setup-db.sql
        # So that the container doesn't shut down, sleep this thread
        sleep infinity